### ISSUE TITLE
Esp8266 para de funcionar 

### ISSUE THREAD

**Issue by wilkensgomes** [alvarowolfx/firebase-sensoriamento#1]
Eu tenho um Nodemcu Esp8266, e eu tenho um problema chato. Depois de um tempo conectado ao banco de dados em tempo real do Firebase ele para de responder aos comandos de saída (eu mudo o comando para desligar o relé e nada acontece), mas ainda recebo os dados de entrada "sensor de temperatura" no meu servidor. Geralmente, o tempo para parar de funcionar é de 30 minutos a 1 hora e retorna à operação normal após a reinicialização.

Será que se eu tenho um problema de configuração de esp, por isso entra em modo de economia?

**Comment by wesley-cantarino** [comment]
Modo economia eu acho que não é pois era para parar de enviar dados também. 

tenta descobrir se função de leitura esta sendo chamada (monitor serial por exemplo) ou tentar dar print no código do erro que esta dando
